//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobs.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid orderId { get; set; }
        public string size { get; set; }
        public string crust { get; set; }
        public string toppings { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string payment { get; set; }
        public bool completed { get; set; }
    }
}
